import React, { Component } from 'react';
import {
  StyleSheet,
  View,
} from 'react-native';
import Menu from './src/Components/MainPages/Interface/MenuBar/menuBar.js'


//NOTE: DO NOT EDIT THIS FILE 
export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Menu />
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
