import React, { Component } from 'react';
import {
  StyleSheet,
  Text,
  View,
  StatusBar
} from 'react-native';
import AppNavigator from './src/app.navigator.js';

// DO NOT EDIT THIS FILE
export default class App extends Component {
  render() {
    return (
        <View style={styles.container}>
        <AppNavigator />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});
